development:
  environment: "sandbox"
  username: "cdeyan_1338373228_biz@yahoo.com"
  password: "1338373255"
  signature: "AtSpke7D7ktK8q6mHkNRR-8I3r0mAKf5oK0siokqoQbCHHwNblZ0Gzoo "
  application_id: "APP-80W284485P519543T"


test:
  environment: "sandbox"
  username: "cdeyan_1338373228_biz@yahoo.com"
  password: "1338373255"
  signature: "AtSpke7D7ktK8q6mHkNRR-8I3r0mAKf5oK0siokqoQbCHHwNblZ0Gzoo "
  application_id: "APP-80W284485P519543T"

production:
  environment: "sandbox"
  username: "cdeyan_1338373228_biz@yahoo.com"
  password: "1338373255"
  signature: "AtSpke7D7ktK8q6mHkNRR-8I3r0mAKf5oK0siokqoQbCHHwNblZ0Gzoo "
  application_id: "APP-80W284485P519543T"
  